mixin () {
  public query func getApiDoc() : async Text {
    "# Travel Intelligence — Backend API\n"
    # "\n"
    # "## Purpose\n"
    # "The Travel Intelligence backend exposes a public, read-only catalog of travel destinations "
    # "(cities, beaches, mountains, countries, and attractions) with rich metadata: coordinates, "
    # "crowd level, a 0–100 Travel Intelligence Score with a factor breakdown, best time to visit, "
    # "budget estimates, and related alternatives. It also provides role-based access control for "
    # "the app's signed-in users and an OQL query surface over the destination catalog.\n"
    # "\n"
    # "## Public methods\n"
    # "\n"
    # "### Destination catalog (public queries — no authentication required)\n"
    # "- `listDestinations() : async [Destination]` — returns the full destination catalog.\n"
    # "- `getDestination(id : Nat) : async ?Destination` — returns one destination by id, or `null` if not found.\n"
    # "- `searchDestinations(searchTerm : Text, category : ?Category) : async [Destination]` — filters the catalog by a case-insensitive text match on name, country, or description, optionally narrowed to a single category (`#city`, `#beach`, `#mountain`, `#country`, `#attraction`). An empty `searchTerm` matches everything.\n"
    # "\n"
    # "### OQL query surface (public — no authentication required)\n"
    # "- `schema() : async Text` — returns the JSON schema of the queryable `destination` entity.\n"
    # "- `execute(qJson : Text) : async Result` — runs a JSON OQL query against the `destination` entity. The entity is registered as `#public_`, so any caller (including anonymous) can read every row. A malformed query traps with `OQL: invalid query — <detail>`.\n"
    # "\n"
    # "### Access control\n"
    # "- `_initialize_access_control() : async ()` — registers the signed-in caller. The first caller to register becomes `#admin`; every later caller becomes `#user`. Anonymous callers are ignored (no-op).\n"
    # "- `_internet_identity_sign_in_start() : async Blob` — begins an Internet Identity sign-in and returns a challenge blob.\n"
    # "- `_internet_identity_sign_in_finish() : async Result<(), Error>` — completes the sign-in and registers the caller's role.\n"
    # "- `getCallerUserRole() : async UserRole` — returns the caller's role (`#admin`, `#user`, or `#guest` for anonymous).\n"
    # "- `assignCallerUserRole(user : Principal, role : UserRole) : async ()` — assigns a role to another principal. Admin only.\n"
    # "- `isCallerAdmin() : async Bool` — returns whether the caller is an admin.\n"
    # "\n"
    # "## Authentication and authorization\n"
    # "\n"
    # "The destination catalog methods (`listDestinations`, `getDestination`, `searchDestinations`) and the OQL `schema`/`execute` methods require **no** authentication — they are world-readable, including for anonymous callers.\n"
    # "\n"
    # "The access-control methods require a signed (non-anonymous) caller:\n"
    # "- `_initialize_access_control`, `_internet_identity_sign_in_finish`, `getCallerUserRole`, `isCallerAdmin`, and `assignCallerUserRole` all act on the caller's identity.\n"
    # "- `getCallerUserRole` returns `#guest` for an anonymous caller; for a signed-in caller who has not yet registered it **traps** with `User is not registered`.\n"
    # "- `assignCallerUserRole` is admin-only; a non-admin caller **traps** with `Unauthorized: Only admins can assign user roles`.\n"
    # "- `isCallerAdmin` returns `false` for anonymous callers and traps for an unregistered signed-in caller (via `getCallerUserRole`).\n"
    # "\n"
    # "### Registration prerequisite\n"
    # "Role-guarded behavior requires registration. A direct API caller registers by calling `_initialize_access_control` once as a signed-in caller before any role-guarded call (guarded queries included). The first initializer receives `#admin`; subsequent callers receive `#user`. An anonymous caller receives `#guest` on `getCallerUserRole` and is ignored by `_initialize_access_control`. A signed-in caller who never registered receives a trap (`User is not registered`) on `getCallerUserRole` and `isCallerAdmin`.\n"
    # "\n"
    # "A caller can be unregistered even when the app already knows it: registration happens only when a principal signs in through the app's own frontend, so a principal that never did so is unregistered even if it belongs to the app's owner. A signed-in caller derived against a different origin is a different principal than the one the frontend registered.\n"
    # "\n"
    # "### Identity derivation\n"
    # "The app's frontend pins an Internet Identity derivation origin, published at `/.well-known/ii-derivation-origin` when available. An agent already holding the user's Internet Identity authorization derives the correct per-app principal against that origin (for example `icp identity link web <name> --app <host>`). Such a delegation acts with the user's full authority in this app until it expires.\n"
    # "\n"
    # "## Units and encodings\n"
    # "- `id` — `Nat`, unique per destination.\n"
    # "- `coordinates.lat` / `coordinates.lng` — `Float`, decimal degrees (WGS84).\n"
    # "- `score` and every `scoreFactors` field (`weather`, `crowd`, `cost`, `traffic`, `activities`) — `Nat` on a 0–100 scale.\n"
    # "- `crowdLevel` — variant `#low` / `#medium` / `#high` (green / yellow / red).\n"
    # "- `category` — variant `#city` / `#beach` / `#mountain` / `#country` / `#attraction`.\n"
    # "- `bestTimeToVisit.bestMonths` — `[Nat]`, 1–12 (January–December). `bestDays` — `[Text]` weekday names. `reason` — `Text`.\n"
    # "- `budget` — `Nat` per-day estimates in USD for `hotel`, `food`, `transport`, `activities`, and `total`.\n"
    # "- `alternatives` — `[Nat]` of related destination ids.\n"
    # "- `imageUrl` — `Text`; a remote image URL (demo imagery).\n"
    # "\n"
    # "## Lifecycle and polling\n"
    # "The destination catalog is static demo data seeded at build time; it does not change at runtime, so there is nothing to poll. The OQL `schema`/`execute` methods are synchronous queries — call them once and read the result directly.\n"
    # "\n"
    # "## Mutation retry safety\n"
    # "The destination catalog methods are read-only queries and have no side effects, so they are safe to retry. `_initialize_access_control` and `_internet_identity_sign_in_finish` are idempotent: registering an already-registered caller is a no-op. `assignCallerUserRole` overwrites the target's role on each call (last write wins).\n"
    # "\n"
    # "## Errors, traps, limits, and gotchas\n"
    # "- `getDestination` returns `null` for an unknown id — it does not trap.\n"
    # "- `getCallerUserRole` and `isCallerAdmin` trap with `User is not registered` for a signed-in but unregistered caller.\n"
    # "- `assignCallerUserRole` traps with `Unauthorized: Only admins can assign user roles` for a non-admin caller.\n"
    # "- `execute` traps with `OQL: invalid query — <detail>` on a malformed query.\n"
    # "- The catalog is **mock/demo data** — clearly label it as such in the UI until real tourism APIs are connected.\n"
    # "- `query` is a reserved keyword in Motoko; the OQL query method is named `execute`.\n"
  };
};
