/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BestTimeToVisit {
  'bestDays' : Array<string>,
  'bestMonths' : Array<bigint>,
  'reason' : string,
}
export interface BudgetEstimate {
  'total' : bigint,
  'hotel' : bigint,
  'food' : bigint,
  'transport' : bigint,
  'activities' : bigint,
}
export type Category = { 'country' : null } |
  { 'city' : null } |
  { 'beach' : null } |
  { 'mountain' : null } |
  { 'attraction' : null };
export interface Cell { 'value' : Value, 'name' : string }
export interface Coordinates { 'lat' : number, 'lng' : number }
export type CrowdLevel = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export interface Destination {
  'id' : bigint,
  'country' : string,
  'name' : string,
  'bestTimeToVisit' : BestTimeToVisit,
  'description' : string,
  'crowdLevel' : CrowdLevel,
  'score' : bigint,
  'imageUrl' : string,
  'category' : Category,
  'scoreFactors' : ScoreFactors,
  'budget' : BudgetEstimate,
  'alternatives' : Array<bigint>,
  'coordinates' : Coordinates,
}
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__1 = { 'ok' : null } |
  { 'err' : Error };
export interface ScoreFactors {
  'cost' : bigint,
  'crowd' : bigint,
  'activities' : bigint,
  'traffic' : bigint,
  'weather' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _SERVICE {
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'execute' : ActorMethod<[string], Result>,
  'getApiDoc' : ActorMethod<[], string>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDestination' : ActorMethod<[bigint], [] | [Destination]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listDestinations' : ActorMethod<[], Array<Destination>>,
  'schema' : ActorMethod<[], string>,
  'searchDestinations' : ActorMethod<
    [string, [] | [Category]],
    Array<Destination>
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];