/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const BestTimeToVisit = IDL.Record({
  'bestDays' : IDL.Vec(IDL.Text),
  'bestMonths' : IDL.Vec(IDL.Nat),
  'reason' : IDL.Text,
});
export const CrowdLevel = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const Category = IDL.Variant({
  'country' : IDL.Null,
  'city' : IDL.Null,
  'beach' : IDL.Null,
  'mountain' : IDL.Null,
  'attraction' : IDL.Null,
});
export const ScoreFactors = IDL.Record({
  'cost' : IDL.Nat,
  'crowd' : IDL.Nat,
  'activities' : IDL.Nat,
  'traffic' : IDL.Nat,
  'weather' : IDL.Nat,
});
export const BudgetEstimate = IDL.Record({
  'total' : IDL.Nat,
  'hotel' : IDL.Nat,
  'food' : IDL.Nat,
  'transport' : IDL.Nat,
  'activities' : IDL.Nat,
});
export const Coordinates = IDL.Record({
  'lat' : IDL.Float64,
  'lng' : IDL.Float64,
});
export const Destination = IDL.Record({
  'id' : IDL.Nat,
  'country' : IDL.Text,
  'name' : IDL.Text,
  'bestTimeToVisit' : BestTimeToVisit,
  'description' : IDL.Text,
  'crowdLevel' : CrowdLevel,
  'score' : IDL.Nat,
  'imageUrl' : IDL.Text,
  'category' : Category,
  'scoreFactors' : ScoreFactors,
  'budget' : BudgetEstimate,
  'alternatives' : IDL.Vec(IDL.Nat),
  'coordinates' : Coordinates,
});

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDestination' : IDL.Func([IDL.Nat], [IDL.Opt(Destination)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listDestinations' : IDL.Func([], [IDL.Vec(Destination)], ['query']),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'searchDestinations' : IDL.Func(
      [IDL.Text, IDL.Opt(Category)],
      [IDL.Vec(Destination)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const BestTimeToVisit = IDL.Record({
    'bestDays' : IDL.Vec(IDL.Text),
    'bestMonths' : IDL.Vec(IDL.Nat),
    'reason' : IDL.Text,
  });
  const CrowdLevel = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const Category = IDL.Variant({
    'country' : IDL.Null,
    'city' : IDL.Null,
    'beach' : IDL.Null,
    'mountain' : IDL.Null,
    'attraction' : IDL.Null,
  });
  const ScoreFactors = IDL.Record({
    'cost' : IDL.Nat,
    'crowd' : IDL.Nat,
    'activities' : IDL.Nat,
    'traffic' : IDL.Nat,
    'weather' : IDL.Nat,
  });
  const BudgetEstimate = IDL.Record({
    'total' : IDL.Nat,
    'hotel' : IDL.Nat,
    'food' : IDL.Nat,
    'transport' : IDL.Nat,
    'activities' : IDL.Nat,
  });
  const Coordinates = IDL.Record({ 'lat' : IDL.Float64, 'lng' : IDL.Float64 });
  const Destination = IDL.Record({
    'id' : IDL.Nat,
    'country' : IDL.Text,
    'name' : IDL.Text,
    'bestTimeToVisit' : BestTimeToVisit,
    'description' : IDL.Text,
    'crowdLevel' : CrowdLevel,
    'score' : IDL.Nat,
    'imageUrl' : IDL.Text,
    'category' : Category,
    'scoreFactors' : ScoreFactors,
    'budget' : BudgetEstimate,
    'alternatives' : IDL.Vec(IDL.Nat),
    'coordinates' : Coordinates,
  });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDestination' : IDL.Func([IDL.Nat], [IDL.Opt(Destination)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listDestinations' : IDL.Func([], [IDL.Vec(Destination)], ['query']),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'searchDestinations' : IDL.Func(
        [IDL.Text, IDL.Opt(Category)],
        [IDL.Vec(Destination)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };